
export const fixedNumbers = [
    {en: "Afghanistan ",rus:  "Афганистан", code:"+93"},
    {en: "Albania", rus: "Албания",code: "+355"},
    {en: "Argentina", rus: "Аргентина",code: "+54"},
    {en: "Armenia", rus: "Армения",code: "+374"},
    {en: "Australia", rus: "Австралия",code: "+61"},
    {en: "Austria", rus: "Австрия",code: "+43"},
    {en: "Azerbaijan", rus: "Азербайджан",code: "+994"},
    {en: "Bahrain", rus: "Бахрейн",code: "+973"},
    {en: "Bangladesh", rus: "Бангладеш",code: "+880"},
    {en: "Belarus", rus: "Беларусь",code: "+375"},
    {en: "Belgium", rus: "Бельгия",code: "+32"},
    {en: "Benin", rus: "Бенин",code: "+229"},
    {en: "Brazil", rus: "Бразилия",code: "+55"},
    {en: "Burma /Myanmar",rus: "Бирма / Мьянма", code:"+95"},
    {en: "Cambodia", rus: "Камбоджа",code: "+855"},
    {en: "Cameroon", rus: "Камерун",code: "+237"},
    {en: "Canada", rus: "Канада",code: "+1"},
    {en: "Chad", rus: "Чад",code: "+235"},
    {en: "Chile", rus: "Чили",code: "+56"},
    {en: "China", rus: "Китай",code: "+86"},
    {en: "Colombia", rus: "Колумбия",code: "+57"},
    {en: "Congo, Dem.Rep", rus:"ДР Конго", code:"+243"},
    {en: "Congo, Republic", rus:"Конго", code:"+242"},
    {en: "Croatia", rus: "Хорватия",code: "+385"},
    {en: "Cyprus", rus: "Кипр",code: "+357"},
    {en: "Czechia", rus: "Чехия",code: "+420"},
    {en: "Denmark", rus: "Дания",code: "+45"},
    {en: "Djibouti", rus: "Джибути",code: "+253"},
    {en: "Egypt", rus: "Египет",code: "+20"},
    {en: "Equatorial Guinearus: ", rus:"Экваториальная Гвинея",code: "+240"},
    {en: "Estonia", rus: "Эстония",code: "+372"},
    {en: "Finland", rus: "Финляндия",code: "+358"},
    {en: "France", rus: "Франция",code: "+33"},
    {en: "Gabon", rus: "Габон",code: "+241"},
    {en: "Georgia", rus: "Грузия",code: "+995"},
    {en: "Germany", rus: "Германия",code: "+49"},
    {en: "Ghana", rus: "Гана",code: "+233"},
    {en: "Greece", rus: "Греция",code: "+30"},
    {en: "Guinea", rus: "Гвинея",code: "+224"},
    {en: "Hong Kongrus: ", rus: "Гонконг",code: "+852"},
    {en: "Hungary", rus: "Венгрия",code: "+36"},
    {en: "India", rus: "Индия",code: "+91"},
    {en: "Indonesia", rus: "Индонезия",code: "62"},
    {en: "Iran", rus: "Иран",code: "+98"},
    {en: "Iraq", rus: "Ирак",code: "+964"},
    {en: "Ireland", rus: "Ирландия",code: "+353"},
    {en: "Israel", rus: "Израиль",code: "+972"},
    {en: "Italy", rus: "Италия",code: "+39"},
    {en: "Ivory Coastrus: ", rus:"Кот-д'Ивуар", code:"+225"},
    {en: "Japan", rus: "Япония",code: "+81"},
    {en: "Jordan", rus: "Иордания",code: "+962"},
    {en: "Kazakhstan", rus: "Казахстан",code: "+7"},
    {en: "Kenya", rus: "Кения",code: "+254"},
    {en: "Kuwait", rus: "Кувейт",code: "+965"},
    {en: "Kyrgyzstan", rus: "Киргизия",code: "+996"},
    {en: "Latvia", rus: "Латвия",code: "+371"},
    {en: "Lebanon", rus: "Ливан",code: "+961"},
    {en: "Libya", rus: "Ливия",code: "+218"},
    {en: "Lithuania", rus: "Литва",code: "+370"},
    {en: "Macao", rus: "Макао",code: "+853"},
    {en: "Macedonia", rus: "Македония",code: "+389"},
    {en: "Madagascar", rus: "Мадагаскар",code: "+261"},
    {en: "Malawi", rus: "Малави",code: "+265"},
    {en: "Malaysia", rus: "Малайзия",code: "+60"},
    {en: "Mali", rus: "Мали",code: "+223"},
    {en: "Malta", rus: "Мальта",code: "+356"},
    {en: "Mauritania", rus: "Мавритания",code: "+222"},
    {en: "Mauritius", rus: "о.code: Маврикий",code: "+230"},
    {en: "Mexico", rus: "Мексика",code: "+52"},
    {en: "Moldova", rus: "Молдавия",code: "+373"},
    {en: "Monaco", rus: "Монако",code: "+377"},
    {en: "Mongolia", rus: "Монголия",code: "+976"},
    {en: "Montserrat", rus: "Монтсеррат",code: "+1"},
    {en: "Morocco", rus: "Марокко",code: "+212"},
    {en: "Namibia", rus: "Намибия",code: "+264"},
    {en: "Nepal", rus: "Непал",code: "+977"},
    {en: "Netherlands", rus: "Нидерланды",code: "+31"},
    {en: "Netherlands Antilles ",rus: "Нидерландские Антильские острова", code:"+599"},
    {en: "New Caledoniarus: ",rus: "Новая Каледония",code: "+687"},
    {en: "New Zealandrus: ", rus:"Новая Зеландия",code: "+64"},
    {en: "Niger", rus: "Нигер",code: "+227"},
    {en: "Nigeria", rus: "Нигерия",code: "+234"},
    {en: "North Korea", rus:"Корейская Народно - Демократическая Республика",code: "+850"},
    {en: "Norway", rus: "Норвегия",code: "+47"},
    {en: "Oman", rus: "Оман",code: "+968"},
    {en: "Pakistan", rus: "Пакистан",code: "+92"},
    {en: "Palestinian territories",rus: "Палестинские территории",code: "+970"},
    {en: "Paraguay", rus: "Парагвай",code: "+595"},
    {en: "Peru", rus: "Перу",code: "+51"},
    {en: "Philippines", rus: "Филиппины",code: "+63"},
    {en: "Poland", rus: "Польша",code: "+48"},
    {en: "Portugal", rus: "Португалия",code: "+351"},
    {en: "Qatar", rus: "Катар",code: "+974"},
    {en: "Réunion", rus: "Реюньон",code: "+262"},
    {en: "Romania", rus: "Румыния",code: "+40"},
    {en: "Russia", rus: "Россия",code: "+7"},
    {en: "Rwanda", rus: "Руанда",code: "+250"},
    {en: "Saint Kittsrus:  and code:Nevis",rus: "Сент-Китс и Невис", code:"+869"},
    {en: "Saudi Arabiarus: ", rus:"code:Саудовская Аравия", code:"+966"},
    {en: "Senegal", rus: "Сенегал",code: "+221"},
    {en: "Serbia", rus: "Сербия",code: "+381"},
    {en: "Seychelles", rus: "Сейшелы",code: "+248"},
    {en: "Sierra Leone", rus:"Сьерра-Леоне",code: "+232"},
    {en: "Singapore", rus: "Сингапур",code: "+65"},
    {en: "Sint Maarten ", rus:"Синт-Мартен", code:"+599"},
    {en: "Slovakia", rus: "Словакия",code: "+421"},
    {en: "Somalia", rus: "Сомали",code: "+252"},
    {en: "South Africarus: ",rus: "code:Южная Африка",code: "+27"},
    {en: "South Korearus: ", rus:"code:Южная Корея", code:"+82"},
    {en: "South Sudanrus: ", rus:"code:Южный Судан", code:"+211"},
    {en: "Spain", rus: "Испания",code: "+34"},
    {en: "Sri Lanka", rus:"Шри-Ланка",code: "+94"},
    {en: "Sudan", rus: "Судан",code: "+249"},
    {en: "Sweden", rus: "Швеция",code: "+46"},
    {en: "Switzerland", rus: "Швейцария",code: "+41"},
    {en: "Syria", rus: "Сирия",code: "+963"},
    {en: "Taiwan", rus: "Тайвань",code: "+886"},
    {en: "Tajikistan", rus: "Таджикистан",code: "+992"},
    {en: "Tanzania", rus: "Танзания",code: "+255"},
    {en: "Thailand", rus: "Таиланд",code: "+66"},
    {en: "Timor-Leste", rus:"Восточный Тимор",code: "+670"},
    {en: "Togo", rus: "Того",code: "+228"},
    {en: "Tunisia", rus: "Тунис",code: "+216"},
    {en: "Turkey", rus: "Турция",code: "+90"},
    {en: "Turkmenistan", rus: "Туркменистан",code: "+993"},
    {en: "Uganda", rus: "Уганда",code: "+256"},
    {en: "Ukraine", rus: "Украина",code: "+380"},
    {en: "United Arabrus:  Emirates",code: "Объединенные Арабские Эмираты",code: "+971"},
    {en: "United Kingdom ",rus: "Великобритания",code: "+44"},
    {en: "United States ",rus: "Соединенные Штаты Америки",code: "+1"},
    {en: "U.Srus: . Virgincode: Islands",rus: "Американские Виргинские острова", code:"+1"},
    {en: "Uzbekistan", rus: "Узбекистан",code: "+998"},
    {en: "Venezuela", rus: "Венесуэла",code: "+58"},
    {en: "Vietnam", rus: "Вьетнам",code: "+84"},
    {en: "Yemen", rus: "Йемен code:", code:"+967"},
    {en: "Zambia", rus: "Замбия",code: "+260"},
    {en: "Zimbabwe", rus: "Зимбабве",code: "+263"}
]